Resources:
  tableAuthenticateSession:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Auth.Session
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: code
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
